recursive_submodules = false
bookmarks = ["/Users/elia.camposilvan/.config", "/Users/elia.camposilvan/.local/bin"]

[shortcuts]
"ctrl-y" = "confirm"

[[search_dirs]]
path = "/Users/elia.camposilvan/.config"
depth = 1

[[search_dirs]]
path = "/Users/elia.camposilvan/go/src/github.com/DataDog"
depth = 1

[[search_dirs]]
path = "/Users/elia.camposilvan/dev"
depth = 1
